### ISSUE TITLE
Make graphql_url a plugin setting

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-big-local#13]
```yaml
plugins:
  datasette-big-local:
    root_dir: /path/to/directory
    graphql_url: https://dev-api.biglocalnews.org/graphql
```
Inspired by https://github.com/palewire/datasette-big-local/commit/7c3019ad00f41900cc26cbcf5547bc8da04cc4d8
